---
- hosts: localhost
  remote_user: root
  tasks:
          - name: Installing Apache web server
            zypper:
                    name: httpd
                    state: latest
            notify:
            - restart apache
          - name: Ensure apache is running
            service:
                    name: apache2
                    state: started
  handlers:
           - name: restart apache
             service:
                     name: apache2
                     state: restarted



