---
- name: configuring httpd.conf file
  template:
           src: httpd.conf.j2
           dest: /etc/httpd/httpd.conf
- name: copying index.html file
  copy:
       src: index.html
       dest: /var/www/html/index.html
  notify:
        - restart httpd

